name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t wholesale-shop-app .

      - name: Verify Docker Image
        run: docker images

      - name: Deployment Complete
        run: echo "Application deployed successfully"